travis:
  secure:
    BINSTAR_TOKEN: aswH6fI85CzWAa3X0LL4srDWqkVWwsbDM+QFIhISS8ZP7/QnezgKziUnoIIZPEdo6oog9zlMRUt4JqznSnHqycmIEdMIyjvbemNvlvZmrZiChyhMOGOm07Gu/nw0O12CNrqdFy2bKl20qKB0cFBmucbmUZqbiZmcAut0+Sntb4bIa7yGZqRYSNmyaov42TGvLo8z0nGV5Bp7f04wPfHDq70x0ASJBWdgqx5nc+Sb2FtUuddxdLwFxUrc842egZAPE3/H1YygViVMRGMxZl8LY4KgL1cZ+6OjlX9OHDVRsy/RdlZLngCA4NBI+r5K8ias3eNw40mbdG6rpHDQxZWrIjOK0akRS7BhhYxAwFOtcFyAoVPfIn1MKsr/Ba6s1ZtlinbFvwqqYHkt9dcufPDIlcaUq7z+jmtUwgU+Fr8garwjb6rGBMbsreaEQADs6KpfY/jWhlYA4SRuIFPSIlhme/c45Y/LQp5oW/1GO7ClUl06JbeFfOJ5lIJFiSEmol5JUvpipi6UoCsLpTsPYJjN0XUbkmo41Lvh/4DWsS916DfC94sdKzIDs9fKMt8koQx2V0JylMB217buZwddbLSVlmo1Kq1YS29zDtV8nDPZdyYuAFx/Lvn2976e8HaY2Z5AGXEraCFrW9iOnDoccTyA/+luOcmv0+KAe8Xs6SG1yME=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
