travis:
  secure:
    BINSTAR_TOKEN: V7+mGMVgNvpWPQSBeV9EtkmAj/PqSIexQoyOleQ1JgGec38yebcl/bvBNhX+C1uggEveO/ypiiwTG/ua5r3tozJ4c9PytU4nh1+OVzSFi3whwSYyodKmcyEeoeH3kXT96wobqrdW8YdnEiu9gU8MnjEDH6QkOJnYrqcAxUQo7Uv9yv2jK/7lqwhxb2wshROPoTXrf0nsZk8/dRjHs2kir+DmqwjtzfAE5fFkw63wA+fnBrCS0hwL4WfChERzszX1ldyNB45AHtlbhFRkp7Xizcph/1ek+AUWiWUfVJaIKo0uTkyYNFm7mZ4F5qrVrd2Q8qUwPSxUe5xXbHztYzV50dg30W7BOQi7NqY13WzURpUII2NjnNxeMcHzLdT9Hva57qZRDLPxpf46ez5We3Tm42cdiOZCU5CeH/aT9VfZXLD7BWa6A24dRol1yHUhxa4Kx2bw/bp8DPdVJmGRw63moDaOuEbuaAASxBnRcebCdqM5yFsfs8Snj4Ckj4xxcNF4qd+4xApw2PCuzpg3V70Vrqq3jbTSHcbdo6KAlW2iQ83DcXEMkGixV3jnA57DIWmnvsPvyuyylgkCy1Hr6tyyHDnGSAP91N19D5+MMj6qX0ofKK76rY2EgWvKDcJDQCd9+qpTY/ijn/Qz4lk8ZEN6btPvdid6DzkqUpqRhgPlWew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
