travis:
  secure:
    BINSTAR_TOKEN: qoTFhLTupmLdRZSC827hq59LekEme4AxRI4qEwUAhrwQXo8adMlUp/Lh5PIZWeSWM64wqdW9DZ2+AE7t2wXIteiHJ0POItSqCgGOI+8CHYTZgcLb94cIE9i9QLOBDWjLLYLEvodDAjU+7jX7hfEVBm3UPYwmlGwB3O70rLBblIausK9MaPOT5frvKEpnEDQxQUJrEOQ0nFy0VqPyfXgz33/azka8tOsw8tu5vNokG72XfStyogqhyG5fzDl/VUSkvUEqe1EQA3OsKPR8ejQwOpoCK/w+a0mTjCt2RqxOFldAkhG1gdObs93e1sN6N621RKrq2x6CK7BdV4hPvEM4YAFFTT27ZtoI4kql7RfpOuyRV/fnGcz30n66UmIbOhe/rJRpRGy1oY8m+Sxcn5cigntWZrZLJV2P5Gr1sdSzkLNc8Ey/UV0YtlSp1WFu3irpNPs3+ZOGbv+GhagLoOAhX6qxMZgbephgQkywRF88OdzBKJ4j7MSwmoqrnzRIwuE1hXvpjnZYoggJ4gi1cVDpvjjg3wRRXk5T0PazkPxu51FriibmUZw4d3Wf2HOXPGQ2UNB/QM39cyHLuJZbHqiON3BHts8uLWBX6RWJ8+JqE5TmqPzjSFRm+MaqX7LXKtAobwKMS9onfsKfxcUTPA0SMR213KUDsDrBmvocqrk/UyM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
