travis:
  secure:
    BINSTAR_TOKEN: DKNL+VCv8PBPSo7Kxrs51dle8yzZn1F/qTbJUCrZ3dspjLR/nRNsfkwgueutD3VCTr/YSB5tzOscCyRUnaAMeBeFVvIPwL9r9MW0S6kqJqnWbJ0W5SAeUK1zCrSM9y46xsziIT9PwfEk1/XzUqPu+Jzn6NRAWShjIlaUKEP/iSTdsUn7g5jDANPej+jLTUyHhFewXqeH67j5sKJTmZxuY3V984IdCjUXlEo1bKHS6BFPW+naYOAFQMYkyX/8KZ8Teb/MU55WZYQ+3Qwylc6HZ3fcCTEuhv5XYvUSifiI6C8lbIYrJFU345Wz91E7d1KS2vooPuMTm2ojHg3WWJOElahe1FxE1amdQ/bYMD8Up2mAKhRl5xbSvcnVFvC/Ggu7QLa70jpfi5nP31kXIFTIJj0hgRzybYeCkEa1VmnDCJFsyzEerv/5Kxm9YUUZ3/Nq66fnWpD/BNjb+MsHYPEbKPLbZ+5XKbCdbplsLzNOJBtAG2GcUlQaJO4l5wxJJEATC0MfurTutayfInLGTC73xlwDNj94nVKGD5zVRXSaoXs9PcgfFLAfALejzpXaAFkPRiDrOiF7oA8OctA54hw+R7mdLkiDPTIQRP7j1owB2H5gGXEDhzJ6axP3CLRxn0k8LKVW7eBBsb95C3WrKOBrBvPQl87C0W97k/ovcqrdNQA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
