travis:
  secure:
    BINSTAR_TOKEN: WcxvAmPMN8+57XoTdV5nHcrKZw1KBUfC/1tbd8DjypXSsRZSv4GKgjJyai/OKNP7UmZz7HJz6/97ZApC0/5jB3UzUpWCRxUCCghlaoBT6jsjOnUZVASWd5T+MRYKzEPu+X2x3N9vXbpQV8XzsWQAOMrRJJ47rNA8NsBQuhWAKdfz9P30b4+mpMLUjCC4p9381boHe89z1cyHP0jS192H1b9hs+TQWEHaYefrkduoNQYj5Wc3f0cXapcTHGHau6HLLcjj0WsS5Gpe9BJH8nW8tCLrZZgoECMRTRPuV5ABBSe2BET+8h7bzXudSmllfSnCtNwcqzxGuzxzdB0Rhen0qAldUiGRk5Kg0f757VG6j1oa+i1qYdjzT6wmKBWKCWPlvh7+3syIVORiwa8rmk6SRbsul1hOFk47VbcjuokBE/XTX6jpURzXQK6W1ozYLkMrd8uR04MeMt+aKrTV/2uo1y0eiYVyKVVzqX+FAwrzGG3RaXRM3feWCJpRASXr3AkpkwpSfY6mEb/l3nweN9Qof3x+RVOXXrwzkDsjnfR1yVpqA7qi5vipk/v8TOUREAm7teJ7TDd+yDBxamW6j774wHXXKQ1bdi6UPEklvQ8ceiAurDKfcw3unc5KZNwPbTHB7dOipFltLCWRt6rDT98RrcgpK99F3j1bBdZImGURan0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
